name: Issue Report
description: Please fill this in to better help the dev help you.
labels: bug
body:
- type: markdown
  attributes:
    value: |
        ### Big thanks for helping OctoFarm grow!

        The OctoFarm developers would prefer people pointing out bugs they find so we can make OctoFarm
        a much more stable platform.

        Plese fill out all required field (*) below to better help the developers understand your issue!

        Failing to do so will waste the developer and your own time in sorting the issue. Thanks!
- type: input
  id: octofarm-version
  attributes:
    label: OctoFarm Version
    placeholder: "latest 1.2"
  validations:
    required: true
- type: input
  id: octoprint-version
  attributes:
    label: OctoPrint Version(s)
    placeholder: "1.5.3, 1.6.0"
  validations:
    required: true
- type: dropdown
  id: process
  attributes:
    label: "pm2 or docker?"
    options:
      - pm2
      - docker
  validations:
    required: true
- type: input
  id: current-system
  attributes:
    label: Operating System
    placeholder: "e.g. Raspberry Pi OS, Ubuntu, Windows"
  validations:
    required: true
- type: input
  id: plugins-octoprint
  attributes:
    label: OctoPrint Plugins
    placeholder: "e.g. bed visualiser, octoklipper, printtimegenius"
- type: dropdown
  id: current-location
  attributes:
    label: "Location of the problem"
    options:
      - Server
      - MongoDb
      - Web Interface
      - Not sure
  validations:
    required: true
- type: textarea
  id: problem-desc
  attributes:
    label: Description of the problem
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    render: markdown
  validations:
    required: true
- type: textarea
  id: repro-steps
  attributes:
    label: Steps taken to reproduce
    description: "How do you trigger this bug? Please walk us through it step by step."
    placeholder: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  id: epected-behaviour
  attributes:
    label: What did you expect to happen
    placeholder: |
      ...
  validations:
    required: true
- type: textarea
  id: avoid-problem
  attributes:
    label: To avoid the problem I had to
    placeholder: |
      ...
- type: markdown
  attributes:
    value: |
      ### Logs
      If you've got access to the System screen it's better to just upload the log dump file as it will
      contain all relevant information for the developers.

      1) **OctoFarm Server logs** Add the system page logs .zip file (if you cant access it, upload your `./logs` folder content here)
      (How to: https://javascript.info/devtools)
      2) **Screenshots / Videos**
      These are always effective, add screenshots to help explain your problem. Try "Peek" on Linux or "ShareX" on Windows.
