/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PrintPausedDto {
  name?: string;
  path?: string;
  origin?: string;
  size?: number;
  position?: {
    e?: number;
    z?: number;
    f?: number;
    y?: number;
    x?: number;
    t?: number;
    [k: string]: any;
  };
  owner?: string;
  user?: string;
  [k: string]: any;
}
