const { randomNumberBetween } = require("../utils/number.util");
const recepticleList = [
  "Ashtray",
  "Bag",
  "Barrel",
  "Basin",
  "Basket",
  "Bedpan",
  "Bin",
  "Box",
  "Briefcase",
  "Buttload",
  "Caddy",
  "Can",
  "Canister",
  "Capsule",
  "Carton",
  "Case",
  "Cask",
  "Casket",
  "Chamber pot",
  "Chest",
  "Cistern",
  "Coffer",
  "Container",
  "Crate",
  "Creel",
  "Cruet",
  "Cuspidor",
  "Drum",
  "Dustpan",
  "Flagon",
  "Flask",
  "Footlocker",
  "Gas Canister",
  "Handbag",
  "Holder",
  "Holster",
  "Hopper",
  "Keg",
  "Kitbag",
  "Ossuary",
  "Pan",
  "Phial",
  "Pitcher",
  "Portfolio",
  "Portmanteau",
  "Potty",
  "Pouch",
  "Purse",
  "Quiver",
  "Reticule",
  "Receptacle",
  "Repository",
  "Reliquary",
  "Saltcellar",
  "Sarcophagus",
  "Satchel",
  "Scabbard",
  "Scuttle",
  "Showcase",
  "Spittoon",
  "Strongbox",
  "Suitcase",
  "Till",
  "Tin",
  "Trough",
  "Trunk",
  "Tub",
  "Urn",
  "Valise",
  "Vat",
  "Wessel",
  "Vial",
  "Vitrine"
];
const foodList = [
  "Asparagus",
  "Broccoli",
  "Carrots",
  "Cauliflower",
  "Celery",
  "Corn",
  "Cucumbers",
  "Lettuce",
  "Mushrooms",
  "Onions",
  "Peppers",
  "Potatoes",
  "Spinach",
  "Squash",
  "Zucchini",
  "Tomatoes",
  "Butter",
  "Cottage Cheese",
  "Milk",
  "Sour Cream",
  "Whipped Cream",
  "Yogurt",
  "Margarine",
  "Bacon",
  "Beef",
  "Chicken",
  "Ground beef",
  "Ham",
  "Pork",
  "Hot dogs",
  "Turkey",
  "Sausage",
  "Apples",
  "Avocados",
  "Bananas",
  "Berries",
  "Cherries",
  "Grapefruit",
  "Grapes",
  "Kiwis",
  "Lemons",
  "Melon",
  "Nectarines",
  "Oranges",
  "Peaches",
  "Pears",
  "Plums",
  "Cookies",
  "Crackers",
  "Dried fruit",
  "Granola",
  "Nuts",
  "Oatmeal",
  "Popcorn",
  "Potato",
  "Pretzels"
];

const maxRecepticle = recepticleList.length;
const maxFood = foodList.length;

const generateRandomName = () => {
  const recepitalName = recepticleList[randomNumberBetween(0, maxRecepticle - 1)];
  const foodName = foodList[randomNumberBetween(0, maxFood - 1)];
  return `${recepitalName} of ${foodName}`;
};

module.exports = {
  generateRandomName
};
