; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=OctoFarm
AppVersion=1.1.13-prerelease
DefaultDirName={autopf}\OctoFarm
OutputBaseFilename=OctoFarm-1.1.13-prerelease
PrivilegesRequired=admin
SetupIconFile=favicon.ico

[Files]
Source: "octofarm-win.exe"; DestDir: "{app}"