name: Bump Server Version Pre-Release
on:
  pull_request:
    types: [ closed ]
    branches:
      - development
    paths-ignore:
      - "server/package.json"
      - "client/package.json"

jobs:
  bump-versions-pre-release:
    name: Bump Versions for pre-release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      # Checkout the development repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN_ACTION }}
