name: Frontend Webpack and NPM Publish
on:
  pull_request:
    types: [ closed ]
    branches:
      - development

jobs:
  bump-client-version:
    if: github.event.pull_request.merged == true
    uses: 'phips28/gh-action-bump-version@master'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PACKAGEJSON_DIR:  'client'
    with:
      minor-wording: '[Minor],add,Adds,new'
      major-wording: '[Major],'
      patch-wording: '[Patch],patch,fixes,fixed'
      rc-wording: '[RC],rc, RC, beta, Beta, Alpha, alpha'
      preid: 'rc'
      target-branch: 'development'
      commit-message: 'CI: bumps client version to {{version}}'
  bump-server-version:
    if: github.event.pull_request.merged == true
    uses: 'phips28/gh-action-bump-version@master'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PACKAGEJSON_DIR:  'server'
    with:
      minor-wording: '[Minor],add,Adds,new'
      major-wording: '[Major],'
      patch-wording: '[Patch],patch,fixes,fixed'
      rc-wording: '[RC],rc, RC, beta, Beta, Alpha, alpha'
      preid: 'rc'
      target-branch: 'development'
      commit-message: 'CI: bumps server version to {{version}}'     `

