name: Bump Server Version Pre-Release
on:
  pull_request:
    types: [ closed ]
    branches:
      - development
    paths-ignore:
      - "server/package.json"
      - "client/package.json"

jobs:
  bump-versions-pre-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Checkout the development repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN_ACTION }}

      # Check to see if changes have occurred in client / server directories
      - name: Detecting changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            server:
            - 'server/**'
            client:
            - 'client/**'+

      # Install node v14 to use.
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      # Up revision the rc version for development
      - if: steps.filter.outputs.server == 'true'
        name: server up revision
        run: npm version prerelease --preid=rc
        working-directory: ./server

        # Up revision the rc version for development
      - name: client up revision
        if: steps.filter.outputs.client == 'true'
        run: npm version prerelease --preid=rc
        working-directory: ./client

      # Build the client for npm publish
      - name: client up revision
        if: steps.filter.outputs.client == 'true'
        run: npm ci --no-optional
        working-directory: ./client
        run: npm run build
        working-directory: ./client

      # Publish the new build to npm
      - name: publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./client/package.json

      # Grab the client package version into a variable.
      - name: get-client-current-version
        id: client-package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: client/package.json

      # Update Server Package with latest client package
      - name: update server client version
        run: npm install @notexpectedyet/octofarm-client@${{ steps.client-package-version.outputs.current-version }} --save
        working-directory: ./server

      # Commit changes to the current development repository
      - name: get-server-current-version
        id: server-package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: server/package.json

        ## commit to repo, and prep pre-release
#      - name: commit-changes-made
#        if: steps.filter.outputs.server == 'true' || steps.filter.outputs.client == 'true'
#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          branch: development
#          commit_message: "[Bot] Bump development versions!"
#          commit_user_name: NotExpectedYet
#          commit_user_email: online@notexpectedyet.com
#          commit_author: James Mackay <online@notexpectedyet.com>
#          tagging_message: ${{ steps.server-package-version.outputs.current-version }}
