name: Docker
on:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - 'master'
      - 'development'
  #workflow_run:
    #workflows: [ "Semantic Release Workflow" ]
    #types:
    #  - completed
jobs:
  docker:
    name: "Docker build"
    runs-on: ubuntu-latest
    steps:
      - name: "Decide tags to use"
        run: |
          if ${{ github.ref == 'refs/heads/master' }} == true; then
            echo 'TAG_EDGE=latest' >> $GITHUB_ENV
          elif ${{ github.ref == 'refs/heads/development' }} == true; then
            echo 'TAG_EDGE=dev' >> $GITHUB_ENV
          fi

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: octofarm/octofarm
          # x.y.z versioning (not strictly 'vx.y.z' semver)
          tag-match: ^(\d+\.)?(\d+\.)?(\*|\d+)$
          tag-custom: |
            ${{env.TAG_EDGE}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Show docker tags"
        run: |
          echo '${{ steps.docker_meta.outputs.tags }}'

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
