name: Docker Monolithic
on:
  pull_request:
  workflow_run:
    workflows: [ Release ]
    types:
      - completed
jobs:
  docker_monolithic:
    name: "Docker build monolithic"
    runs-on: ubuntu-latest
    steps:
      - name: "Decide tags to use"
        run: |
          if ${{ github.ref == 'refs/heads/master' }} == true; then
            echo 'TAG_EDGE=monolithic-latest' >> $GITHUB_ENV
          fi

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: octofarm/octofarm
          tag-latest: false
          tag-custom: |
            ${{env.TAG_EDGE}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Show docker tags"
        run: |
          echo '${{ steps.docker_meta.outputs.tags }}'

      - name: Build and push (monolithic)
        id: docker_build_monolithic
        uses: docker/build-push-action@v2
        with:
          file: ./monolithic.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
