name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.TOKEN_ACTION }}
        issue-message: "Big thanks for submitting a bug report! I'm currently a one man band and I will get back to you as soon as possible!"
        pr-message: "Big thanks for submitting this PR and making OctoFarm grow! Your review will be coming shortly!"
