name: Greetings From the Dev

on:
  issues:
    types: [opened]
  pull_request:
    branches: [main]
    types: [opened]


jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.TOKEN_ACTION }}
        issue-message: |
          Big thanks for submitting a bug report! 
          
          I'm currently a one man band and I will get back to you as soon as possible!
        pr-message: |
          Big thanks for submitting this PR and making OctoFarm grow! 
          
          Your review will be coming shortly!
          
          Please note the following:
          
          - Make sure to format your PR title accordingly! https://github.com/conventional-changelog/commitlint
          - If you'd like your name in the release, please @username your commits.
          - If you're fixing a bug, then please reference the issue number in the description
          - If you're adding a new feature, then please check with @notexpectedyet that it will be accepted.
