/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OctoPrintSettingsDto {
    api?: {
        allowCrossOrigin?: boolean;
        key?: string;
        [k: string]: any;
    };
    appearance?: {
        closeModalsWithClick?: boolean;
        color?: string;
        colorIcon?: boolean;
        colorTransparent?: boolean;
        defaultLanguage?: string;
        fuzzyTimes?: boolean;
        name?: string;
        showFahrenheitAlso?: boolean;
        showInternalFilename?: boolean;
        [k: string]: any;
    };
    devel?: {
        pluginTimings?: boolean;
        [k: string]: any;
    };
    feature?: {
        autoUppercaseBlacklist?: string[];
        g90InfluencesExtruder?: boolean;
        keyboardControl?: boolean;
        modelSizeDetection?: boolean;
        pollWatched?: boolean;
        printCancelConfirmation?: boolean;
        printStartConfirmation?: boolean;
        sdSupport?: boolean;
        temperatureGraph?: boolean;
        [k: string]: any;
    };
    folder?: {
        logs?: string;
        timelapse?: string;
        timelapseTmp?: string;
        uploads?: string;
        watched?: string;
        [k: string]: any;
    };
    gcodeAnalysis?: {
        runAt?: string;
        [k: string]: any;
    };
    plugins?: {
        action_command_notification?: {
            enable?: boolean;
            enable_popups?: boolean;
            [k: string]: any;
        };
        action_command_prompt?: {
            command?: string;
            enable?: string;
            enable_emergency_sending?: boolean;
            enable_signal_support?: boolean;
            [k: string]: any;
        };
        announcements?: {
            channel_order?: string[];
            channels?: {
                _blog?: {
                    description?: string;
                    name?: string;
                    priority?: number;
                    read_until?: number;
                    type?: string;
                    url?: string;
                    [k: string]: any;
                };
                _important?: {
                    description?: string;
                    name?: string;
                    priority?: number;
                    read_until?: number;
                    type?: string;
                    url?: string;
                    [k: string]: any;
                };
                _octopi?: {
                    description?: string;
                    name?: string;
                    priority?: number;
                    read_until?: number;
                    type?: string;
                    url?: string;
                    [k: string]: any;
                };
                _plugins?: {
                    description?: string;
                    name?: string;
                    priority?: number;
                    read_until?: number;
                    type?: string;
                    url?: string;
                    [k: string]: any;
                };
                _releases?: {
                    description?: string;
                    name?: string;
                    priority?: number;
                    read_until?: number;
                    type?: string;
                    url?: string;
                    [k: string]: any;
                };
                [k: string]: any;
            };
            display_limit?: number;
            enabled_channels?: string[];
            forced_channels?: string[];
            summary_limit?: number;
            ttl?: number;
            [k: string]: any;
        };
        backup?: {
            restore_unsupported?: boolean;
            [k: string]: any;
        };
        discovery?: {
            addresses?: null;
            httpPassword?: null;
            httpUsername?: null;
            interfaces?: null;
            model?: {
                description?: null;
                name?: null;
                number?: null;
                serial?: null;
                url?: null;
                vendor?: null;
                vendorUrl?: null;
                [k: string]: any;
            };
            pathPrefix?: null;
            publicHost?: null;
            publicPort?: null;
            upnpUuid?: string;
            zeroConf?: any[];
            [k: string]: any;
        };
        errortracking?: {
            enabled?: boolean;
            enabled_unreleased?: boolean;
            unique_id?: string;
            url_coreui?: string;
            url_server?: string;
            [k: string]: any;
        };
        firmware_check?: {
            ignore_infos?: boolean;
            [k: string]: any;
        };
        gcodeviewer?: {
            mobileSizeThreshold?: number;
            sizeThreshold?: number;
            [k: string]: any;
        };
        pi_support?: {
            ignore_unrecommended_model?: boolean;
            vcgencmd_throttle_check_command?: string;
            vcgencmd_throttle_check_enabled?: boolean;
            [k: string]: any;
        };
        pluginmanager?: {
            confirm_disable?: boolean;
            dependency_links?: boolean;
            hidden?: any[];
            ignore_throttled?: boolean;
            notices?: string;
            notices_ttl?: number;
            pip_args?: null;
            pip_force_user?: boolean;
            repository?: string;
            repository_ttl?: number;
            [k: string]: any;
        };
        softwareupdate?: {
            cache_ttl?: number;
            check_overlay_ttl?: number;
            check_overlay_url?: string;
            credentials?: {
                [k: string]: any;
            };
            ignore_throttled?: boolean;
            minimum_free_storage?: number;
            notify_users?: boolean;
            octoprint_branch_mappings?: {
                branch: string;
                commitish: string[];
                name: string;
                [k: string]: any;
            }[];
            octoprint_checkout_folder?: null;
            octoprint_method?: string;
            octoprint_pip_target?: string;
            octoprint_release_channel?: string;
            octoprint_tracked_branch?: null;
            octoprint_type?: string;
            pip_command?: null;
            pip_enable_check?: boolean;
            [k: string]: any;
        };
        tracking?: {
            enabled?: boolean;
            events?: {
                commerror?: boolean;
                plugin?: boolean;
                pong?: boolean;
                printer?: boolean;
                printer_safety_check?: boolean;
                printjob?: boolean;
                slicing?: boolean;
                startup?: boolean;
                throttled?: boolean;
                update?: boolean;
                [k: string]: any;
            };
            ping?: null;
            pong?: number;
            server?: null;
            unique_id?: string;
            [k: string]: any;
        };
        virtual_printer?: {
            ambientTemperature?: number;
            brokenM29?: boolean;
            brokenResend?: boolean;
            busyInterval?: number;
            capabilities?: {
                AUTOREPORT_SD_STATUS?: boolean;
                AUTOREPORT_TEMP?: boolean;
                EMERGENCY_PARSER?: boolean;
                [k: string]: any;
            };
            commandBuffer?: number;
            echoOnM117?: boolean;
            enable_eeprom?: boolean;
            enabled?: boolean;
            errors?: {
                checksum_mismatch?: string;
                checksum_missing?: string;
                command_unknown?: string;
                lineno_mismatch?: string;
                lineno_missing?: string;
                maxtemp?: string;
                mintemp?: string;
                [k: string]: any;
            };
            firmwareName?: string;
            forceChecksum?: boolean;
            hasBed?: boolean;
            hasChamber?: boolean;
            includeCurrentToolInTemps?: boolean;
            includeFilenameInOpened?: boolean;
            klipperTemperatureReporting?: boolean;
            m105NoTargetFormatString?: string;
            m105TargetFormatString?: string;
            m114FormatString?: string;
            m115FormatString?: string;
            m115ReportCapabilities?: boolean;
            numExtruders?: number;
            okAfterResend?: boolean;
            okBeforeCommandOutput?: boolean;
            okFormatString?: string;
            pinnedExtruders?: null;
            preparedOks?: any[];
            repetierStyleTargetTemperature?: boolean;
            reprapfwM114?: boolean;
            resend_ratio?: number;
            resetLines?: string[];
            rxBuffer?: number;
            sdFiles?: {
                longname?: boolean;
                size?: boolean;
                [k: string]: any;
            };
            sendBusy?: boolean;
            sendWait?: boolean;
            sharedNozzle?: boolean;
            simulateReset?: boolean;
            smoothieTemperatureReporting?: boolean;
            supportF?: boolean;
            supportM112?: boolean;
            support_M503?: boolean;
            throttle?: number;
            waitInterval?: number;
            [k: string]: any;
        };
        [k: string]: any;
    };
    printer?: {
        defaultExtrusionLength?: number;
        [k: string]: any;
    };
    scripts?: {
        gcode?: {
            afterPrintCancelled?: string;
            "snippets/disable_bed"?: string;
            "snippets/disable_hotends"?: string;
            [k: string]: any;
        };
        [k: string]: any;
    };
    serial?: {
        abortHeatupOnCancel?: boolean;
        ackMax?: number;
        additionalBaudrates?: any[];
        additionalPorts?: any[];
        alwaysSendChecksum?: boolean;
        autoconnect?: boolean;
        baudrate?: number;
        baudrateOptions?: number[];
        blacklistedBaudrates?: any[];
        blacklistedPorts?: any[];
        blockWhileDwelling?: boolean;
        blockedCommands?: string[];
        capAutoreportSdStatus?: boolean;
        capAutoreportTemp?: boolean;
        capBusyProtocol?: boolean;
        capEmergencyParser?: boolean;
        checksumRequiringCommands?: string[];
        disableSdPrintingDetection?: boolean;
        disconnectOnErrors?: boolean;
        emergencyCommands?: string[];
        exclusive?: boolean;
        externalHeatupDetection?: boolean;
        firmwareDetection?: boolean;
        helloCommand?: string;
        ignoreErrorsFromFirmware?: boolean;
        ignoreIdenticalResends?: boolean;
        log?: boolean;
        logPositionOnCancel?: boolean;
        logPositionOnPause?: boolean;
        longRunningCommands?: string[];
        maxTimeoutsIdle?: number;
        maxTimeoutsLong?: number;
        maxTimeoutsPrinting?: number;
        neverSendChecksum?: boolean;
        notifySuppressedCommands?: string;
        pausingCommands?: string[];
        port?: null;
        portOptions?: any[];
        repetierTargetTemp?: boolean;
        resendRatioStart?: number;
        resendRatioThreshold?: number;
        sanityCheckTools?: boolean;
        sdAlwaysAvailable?: boolean;
        sdRelativePath?: boolean;
        sendM112OnError?: boolean;
        supportResendsWithoutOk?: string;
        swallowOkAfterResend?: boolean;
        timeoutBaudrateDetectionPause?: number;
        timeoutCommunication?: number;
        timeoutCommunicationBusy?: number;
        timeoutConnection?: number;
        timeoutDetectionConsecutive?: number;
        timeoutDetectionFirst?: number;
        timeoutPositionLogWait?: number;
        timeoutSdStatus?: number;
        timeoutSdStatusAutoreport?: number;
        timeoutTemperature?: number;
        timeoutTemperatureAutoreport?: number;
        timeoutTemperatureTargetSet?: number;
        triggerOkForM29?: boolean;
        useParityWorkaround?: string;
        waitForStart?: boolean;
        [k: string]: any;
    };
    server?: {
        allowFraming?: boolean;
        commands?: {
            serverRestartCommand?: string;
            systemRestartCommand?: null;
            systemShutdownCommand?: null;
            [k: string]: any;
        };
        diskspace?: {
            critical?: number;
            warning?: number;
            [k: string]: any;
        };
        onlineCheck?: {
            enabled?: boolean;
            host?: string;
            interval?: number;
            name?: string;
            port?: number;
            [k: string]: any;
        };
        pluginBlacklist?: {
            enabled?: boolean;
            ttl?: number;
            url?: string;
            [k: string]: any;
        };
        [k: string]: any;
    };
    system?: {
        actions?: any[];
        events?: null;
        [k: string]: any;
    };
    temperature?: {
        cutoff?: number;
        profiles?: {
            bed: number;
            chamber: null;
            extruder: number;
            name: string;
            [k: string]: any;
        }[];
        sendAutomatically?: boolean;
        sendAutomaticallyAfter?: number;
        [k: string]: any;
    };
    terminalFilters?: {
        name: string;
        regex: string;
        [k: string]: any;
    }[];
    webcam?: {
        bitrate?: string;
        ffmpegPath?: string;
        ffmpegThreads?: number;
        ffmpegVideoCodec?: string;
        flipH?: boolean;
        flipV?: boolean;
        rotate90?: boolean;
        snapshotSslValidation?: boolean;
        snapshotTimeout?: number;
        snapshotUrl?: string;
        streamRatio?: string;
        streamTimeout?: number;
        streamUrl?: string;
        timelapseEnabled?: boolean;
        watermark?: boolean;
        webcamEnabled?: boolean;
        [k: string]: any;
    };

    [k: string]: any;
}
