/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OctoPrintSessionDto {
  _is_external_client?: boolean;
  _login_mechanism?: string;
  active?: boolean;
  admin?: boolean;
  apikey?: string;
  groups?: string[];
  name?: string;
  needs?: {
    group?: string[];
    role?: string[];
    [k: string]: any;
  };
  permissions?: any[];
  roles?: string[];
  session?: string;
  settings?: {
    interface?: {
      language?: string;
      [k: string]: any;
    };
    [k: string]: any;
  };
  user?: boolean;
  [k: string]: any;
}
